# Auto-generated list of locations and event types

locations = [
    "*60 Fellowship Drive Reserve  (Hall) - Doonan",
    "*Alexandra Headland - Other",
    "*Alexandra Headland Beach BA154 (Seaforth Park)",
    "*Alexandra Headland Beach BA155 (Buhk Family Park)",
    "*Alexandra Headland Beach BA156 (Buhk Family Park)",
    "*Alexandra Headland Beach BA157/Skate Bowl (Buhk Family Park)",
    "*Alexandra Headland Beach BA158 (Buhk Family Park/SLSC)",
    "*Alexandra Headland Beach BA159 (Buhk Family Park/SLSC)",
    "*Alexandra Headland Beach BA160 (Wilkes Family Park/SLSC)",
    "*Alexandra Headland Beach BA161 (Wilkes Family Park)",
    "*Alexandra Headland Beach BA162",
    "*Alexandra Headland Beach BA163",
    "*Alexandra Headland Beach BA164",
    "*Alexandra Headland Beach BA165",
    "*Alexandra Headland Beach BA166 (The Bluff)",
    "*Alexandra Headland Beach BA167 (The Bluff)",
    "*Alexandra Headland Beach BA168 (Churinga Park/HMAS Brisbane)",
    "*Anzac Park - Victoria Tce ( -Wickham Point) - Kings Beach",
    "*Apex Park - Esplanade  - Golden Beach (BA320)",
    "*Arthur Parkyn Park - Mooloolaba (BA180-182)",
    "*Ayliffe Park - Esplanade  - Golden Beach (BA309-314)",
    "*Ballinger Beach Park -   - Buderim St - Currimundi (BA260)",
    "*Balmoral Lookout (Near  Montville Rd Service Lne) - Maleny-Montville Rd",
    "*Baringa - Other",
    "*Baringa Community Facilities - (Outside Baringa Community Centre - ) - Baringa",
    "*Baringa Town Square & Skate Bowl (Parallel to Baringa Community Centre - ) - Baringa",
    "*Beerwah - Other",
    "*Beerwah Sports Ground -  - 32 Sportsground Dr - Beerwah",
    "*Beerwah Tower Green (Railway Stn) - Simpson St - Beerwah",
    "*Ben Bennett Bushland Park -  - 106 Queen Street - Caloundra",
    "*Bicentennial Park - Bicentenary Lane - Maleny",
    "*Big Pineapple(Private Land) - 76 Nambour Connection Rd - Woombye",
    "*Birrahl Park - David Low Way - Yaroomba (BA90)",
    "*Birtinya - Other",
    "*Black Swan Park - Cotton Tree",
    "*Bli Bli - Other",
    "*Boardwalk Beach Mount Coolum BA94",
    "*Boardwalk Beach Mount Coolum BA95",
    "*Boardwalk Beach Mount Coolum BA96 / Boardwalk Platform",
    "*Boardwalk Beach Mount Coolum BA97",
    "*Bokarina - Other",
    "*Bokarina Beach BA 239 (Wyanda Park)",
    "*Bokarina Beach Park ( &  playground) Bokarina Bvd/Singlefin Cres",
    "*Bray Road Park - Mooloolah Valley",
    "*Brightwater Community Lake Park (The Lakeside Lawn) - Amberjack St - Mountain Creek",
    "*Buddina Beach BA207 (Alan Walker Park)",
    "*Buddina Beach BA207-219  (Alan Walker Park)",
    "*Buderim - Other",
    "*Buderim Forest Park  - Lindsay Rd - Buderim",
    "*Buderim Village District Park & Carpark - 2 King Street - Buderim",
    "*Buhk Family Park - Alexandra Headland (BA155-160)",
    "*Bulcock Beach  BA 296 (Bulcock Beach carpark)",
    "*Bulcock Beach - Esplanade - Caloundra BA293-301",
    "*Bulcock Beach BA 293 (Happy Valley carpark)",
    "*Bulcock Beach BA 294 (Happy Valley carpark)",
    "*Bulcock Beach BA 298",
    "*Bulcock Beach BA295 (Bulcock Beach carpark)",
    "*Bulcock Beach BA297",
    "*CLP Private Land Event - Non listed locations",
    "*Caloundra - Approved Street Stall Location - 43 Bulcock St",
    "*Caloundra - Other",
    "*Caloundra Skate Park - Central Park -  - 81-239 Arthur St - Caloundra",
    "*Caloundra West - Other - Caloundra West",
    "*Centaur Park -  Esplanade Headland - Kings Beach",
    "*Chambers Island Park -  - Bradman Ave - Maroochydore",
    "*Charles Clarke Park - River Esp - Mooloolaba",
    "*Cheese Block Park - Urunga Esp (Mooloolaba Cove) (BA190)",
    "*Churinga - Alex Bluff Foreshore Park & Carpark - HMAS Brisbane - Alexandra Headland",
    "*Clarke Place Park - Happy Valley - Esplanade Bulcock Beach - (BA293-295)",
    "*Cliff Hargreaves Park -  - Westaway Pde - Currimundi (BA254)",
    "*Cooloolathin Park - Alexandra Parade Service Rd - Alexandra Headland (BA155)",
    "*Coolum - Other - Coolum Beach",
    "*Coolum Beach  BA72 (Lions & Norrie Job Park)",
    "*Coolum Beach  BA75 (Caravan Park)",
    "*Coolum Beach BA69 (Stumers Creek)",
    "*Coolum Beach BA70 (Stumers Creek)",
    "*Coolum Beach BA71 (Stumers Creek)",
    "*Coolum Beach BA73 (Caravan Park)",
    "*Coolum Beach BA74 (Caravan Park)",
    "*Coolum Beach BA76 (Caravan Park)",
    "*Coolum Beach BA77 (Tickle Park North)",
    "*Coolum Beach BA78 (Tickle Park/SLSC )",
    "*Coolum Beach BA79 (SLSC )",
    "*Coolum Beach BA80 (SLSC )",
    "*Coolum Beach BA81 (Boardwalk entrance)",
    "*Coolum Beach North BA68 (68",
    "*Coopers Lookout Pk/KawanaSLSC - Buddina (BA220-224)",
    "*Cotton Tree Beach BA137 (Boat Shed Restaurant)",
    "*Cotton Tree Beach BA137-140",
    "*Cotton Tree Beach BA139 (Caravan Park)",
    "*Cotton Tree Beach BA140 (Caravan Park)",
    "*Cotton Tree Park - Cotton Tree",
    "*Crummunda Park - Coongarra Esp - Wurtulla",
    "*Currimundi - Other",
    "*Currimundi Beach BA254 Buderim St Reserve (Westway Pde)",
    "*Currimundi Beach BA254-261",
    "*Currimundi Beach BA255 Buderim St Reserve (Watson St)",
    "*Currimundi Beach BA256 Buderim St Reserve (Robe St)",
    "*Currimundi Beach BA258 Buderim St Reserve",
    "*Currimundi Beach BA260 Buderim St Reserve (Buderim St)",
    "*Currimundi Beach BA261 Buderim St Reserve (Buderim St South)",
    "*Des Scanlan Park - Cotton Tree",
    "*Dick Caplick Park  - 8-16 Napier Rd - Eumundi",
    "*Dicky Beach - Other",
    "*Dicky Beach BA262 (Beerwah Pde Park -Ann St)",
    "*Dicky Beach BA262-271",
    "*Dicky Beach BA263 (Beerwah Pde Park -Bell St)",
    "*Dicky Beach BA264 (Beerwah Pde Park -SLSC carpark)",
    "*Dicky Beach BA265 (Beerwah Pde Park -SLSC carpark)",
    "*Dicky Beach BA266 (Sir Leslie Wilson Park)",
    "*Dicky Beach BA267 (Sir Leslie Wilson Park)",
    "*Dicky Beach BA268 (Sir Leslie Wilson Park)",
    "*Dicky Beach BA269 (Sir Leslie Wilson Park)",
    "*Dicky Beach BA270",
    "*Dicky Beach BA271 (Cooroora St)",
    "*Dicky Beach Park -  - (Caravan & Skate Park BA265-267) - Dicky Beach",
    "*Discovery Beach - Marcoola BA113 (Surfair)",
    "*Discovery Beach - Marcoola BA113-116",
    "*Double Bay Beach Park - Kawana Island - Grand Parade",
    "*Eddie De Vere Courtyard (Library) - Nambour",
    "*Eleanor Shipley Park - Seaview Tce - Moffat Beach",
    "*Elizabeth Daniels Park & Lions Pk  - Buderim",
    "*Eudlo - Other",
    "*Eumundi - Other",
    "*Eumundi Amphitheatre & Parkland  -20-56 Napier Rd - Eumundi",
    "*Federation Park -  - 23 Primrose Ct - Palmwoods",
    "*Felicity Park -  - 18 Omrah Ave - Caloundra",
    "*Felix Parry Park - Marcoola (BA104-105)",
    "*First Bay Coolum Beach BA82",
    "*First Jetty Cotton Tree - The Arena (By S/Pool)",
    "*Flintwood Cresent Park - Palmview",
    "*Foote Memorial Sanctuary Park   - Buderim",
    "*Foundation Square  - South Sea Islander Way - Maroochydore",
    "*Fraser Park - Esplanade  - Golden Beach",
    "*Gardners Falls Park - Obi Lane - South Maleny",
    "*Glass House Mountains - Other",
    "*Glen Retreat Park - Town of Seaside - Marcoola",
    "*Glenfields Friendship Park (Arana Park) Mountain Creek",
    "*Golden Beach - Other",
    "*Golden Beach BA303",
    "*Golden Beach BA304",
    "*Golden Beach BA305",
    "*Golden Beach BA306",
    "*Golden Beach BA307",
    "*Golden Beach BA309 (Ayliffe Park)",
    "*Golden Beach BA320 (Apex Pk/PBoat)",
    "*Grahame Stewart Park - Currimundi Rd - Currimundi",
    "*Green Park - Conondale Memorial Recreation Park  - Elaman Creek",
    "*Harmony Boulevard Park Sth - Palmview",
    "*Hyatt Beach - Yaroomba BA91",
    "*Hyatt Beach - Yaroomba BA91-93",
    "*Jack Morgan Park - Coolum Beach",
    "*Jensen Park - Esplanade  - Golden Beach",
    "*Jessica Park - Nicklin Way - Minyama",
    "*Kawana Beach - BA220- (Coopers L/OutPk) Buddina",
    "*Kawana Beach - BA220-228 - (Coopers L/OutPk) Buddina",
    "*Kawana Beach - BA221- (Coopers L/OutPk) Buddina",
    "*Kawana Beach - BA222- (Coopers L/OutPk) Buddina",
    "*Kawana Beach - BA223- (Coopers L/OutPk) Buddina",
    "*Kenilworth - Other",
    "*Kenilworth Showgrounds - 3726 Maleny Kenilworth Rd - Kenilworth",
    "*Kenilworth Town Park - Kenilworth",
    "*Kevin Asmus Park - 20 Nanyima Street - Buddina",
    "*Kings Beach BA283 (Fountain&Pool)",
    "*Kings Beach BA284 (Lions Pk/Headland Carpark)",
    "*Kings Beach BA285 (Ormonde Tce)",
    "*Kings Beach BA286 (Ormonde Tce)",
    "*Kings Beach BA287 (Ormonde Tce)",
    "*Kings Beach BA288 (Ormonde Tce)",
    "*Kings Beach BA289 (Levuka Ave)",
    "*Kings Beach BA290 (Merrima Ave)",
    "*Kings Beach BA291 (Dingle Ave)",
    "*Kings Beach BA292 (Dingle Ave)",
    "*Kings Beach Park (Amphi & Stage",
    "*Kings Beach Park -  Kings Beach",
    "*Kings Beach Park - Ormonde Tce -806 - Kings Beach (BA285-289)",
    "*Kirbys Road Environmental Reserve  - Obi Obi",
    "*La Balsa Park ( -Inc. Rotunda) - Buddina",
    "*Lake Kawana Waterfront Park -  - Sportsmans Pde - Bokarina",
    "*Landsborough Museum  - 4 Maleny St Service Lne - Landsborough",
    "*Leach Park -  -15 Short Street - Golden Beach (BA302)",
    "*Lions Park & Fountain/Headland Carpark -  - Kings Beach (BA283-284)",
    "*Lions and Norrie Job Park - Coolum Beach (BA72)",
    "*Maleny - Approved Street Stall Location - 26 Maple St",
    "*Maleny - Other - Maleny",
    "*Maleny Showgrounds - Maleny-Stanley River Rd - Maleny",
    "*Mapleton Lillyponds - 10 Delicia Road - Mapleton",
    "*Mapleton RSL Memorial Pk - 8 Flaxton Dr - Mapleton",
    "*Marcoola Beach BA103 (vehicle access SLSC)",
    "*Marcoola Beach BA104 (northern Felix Parry Park)",
    "*Marcoola Beach BA105 (Felix Parry Park)",
    "*Marcoola Beach BA106",
    "*Marcoola Beach BA107",
    "*Marcoola Beach BA108",
    "*Marcoola Beach BA109",
    "*Marcoola Beach BA110",
    "*Marcoola Beach BA111",
    "*Marcoola Beach BA112",
    "*Maroochy Botanical Gardens - Bushland Sculpture Garden - Tanawha",
    "*Maroochy Botanical Gardens - Contemplation Garden - Tanawha",
    "*Maroochy Botanical Gardens - Friendship Colonnade - Tanawha",
    "*Maroochy Botanical Gardens - Open Lawn - Tanawha",
    "*Maroochy Botanical Gardens - Tanawha",
    "*Maroochy Lions Park -  -  Fishermans Road - Maroochydore",
    "*Maroochydore - Other - Maroochydore",
    "*Maroochydore Beach BA141",
    "*Maroochydore Beach BA141-153",
    "*Maroochydore Beach BA142",
    "*Maroochydore Beach BA143",
    "*Maroochydore Beach BA144",
    "*Maroochydore Beach BA145",
    "*Maroochydore Beach BA146",
    "*Maroochydore Beach BA147",
    "*Maroochydore Beach BA148",
    "*Maroochydore Beach BA149",
    "*Maroochydore Beach BA150",
    "*Maroochydore Beach BA151",
    "*Maroochydore Beach BA152",
    "*Maroochydore Beach BA153",
    "*Mary Cairncross Scenic Reserve (Butterfly Deck) - Maleny",
    "*MaryBell Park - Baringa -",
    "*Minyama Other - Minyama",
    "*Moffat Beach - Other - Moffat Beach",
    "*Moffat Beach - Queen of Colonies Parade BA272-275",
    "*Moffat Beach - Queen of Colonies Parade BA274",
    "*Moffat Beach - Queen of Colonies Parade BA275",
    "*Moffat Beach Park - Queen of Colonies Parade - Moffat Beach",
    "*Monash Park Esplanade  - Golden Beach (BA319a-320)",
    "*Montville Village Green (Memorial Close) - Main St",
    "*Mooloolaba - Other - Mooloolaba",
    "*Mooloolaba Foreshore Park (BA171-179) - Beach Tce to SLSC",
    "*Mooloolaba Main Beach BA169 - (Northern Parklands)",
    "*Mooloolaba Main Beach BA169-179",
    "*Mooloolaba Main Beach BA170 - (Northern Parklands)",
    "*Mooloolaba Main Beach BA174 - (Beach Tce)",
    "*Mooloolaba Main Beach BA175 - (Beach Tce)",
    "*Mooloolaba Main Beach BA176 - (Mooloolaba Esp)",
    "*Mooloolaba Main Beach BA177 - (Mooloolaba Esp)",
    "*Mooloolaba Main Beach BA178 - (Mooloolaba Esp)",
    "*Mooloolaba Main Beach BA179 - (Club Lane - Mool Esp)",
    "*Mooloolaba Spit Beach BA180 - (Club Lane -Arthur Parkyn Pk)",
    "*Mooloolaba Spit Beach BA180-195",
    "*Mooloolaba Spit Beach BA181 - (Arthur Parkyn Pk/Caravan Pk)",
    "*Mooloolaba Spit Beach BA182 - (Arthur Parkyn Pk/Caravan Pk)",
    "*Mooloolaba Spit Beach BA183 - (Caravan Pk/Boardwalk)",
    "*Mooloolaba Spit Beach BA184 - (Urunga Esp/Boardwalk)",
    "*Mooloolaba Spit Beach BA185 - (Urunga Esp/Boardwalk)",
    "*Mooloolaba Spit Beach BA186 - (Penny Lane/Boardwalk)",
    "*Mooloolaba Spit Beach BA187 - (Penny Lane/Boardwalk)",
    "*Mooloolaba Spit Beach BA188 - (Penny Lane/Boardwalk)",
    "*Mooloolaba Spit Beach BA189 - (Urunga Esp/Boardwalk)",
    "*Mooloolaba Spit Beach BA190 - (Urunga Esp)",
    "*Mooloolaba Spit Beach BA191 - (Pirate Ship Pk West/Parkyn Pde)",
    "*Mooloolaba Spit Beach BA192 - (Pirate Ship Pk Centre/Parkyn Pde)",
    "*Mooloolaba Spit Beach BA193 - (Pirate Ship Pk East/Parkyn Pde)",
    "*Mooloolaba Spit Beach BA194 - (Rotary Pk/Parkyn Pde)",
    "*Mooloolaba Spit Beach BA195 - (Spit Reserve/Parkyn Pde)",
    "*Mooloolaba Spit Parkland - (Marina Grove) - Mooloolah River",
    "*Mooloolaba Spit Rock Wall/Parkland - (Osprey Gardens) - (BA195)",
    "*Mooloolah River Park - (Penny Lane Park) - Mooloolaba",
    "*Mooloolah Valley Country Club (Private Land) -129 Connection Rd",
    "*Mooloolah Valley Sportsground - 135 Connection Rd - Landsborough",
    "*Moorings Park - 5 Undanbi Lane - Twin Waters",
    "*Mudjimba Beach BA117 (Northern End Carpark)",
    "*Mudjimba Beach BA117-130",
    "*Mudjimba Beach BA118",
    "*Mudjimba Beach BA119",
    "*Mudjimba Beach BA120",
    "*Mudjimba Beach BA121",
    "*Mudjimba Beach BA122",
    "*Mudjimba Beach BA123 (SLSC vehicle access)",
    "*Mudjimba Beach BA125 (Power Memorial Park Southern end)",
    "*Muller Park - 319-323 David Low Way - Bli Bli",
    "*Nambour Other - Nambour",
    "*Nambour Town Square - Nambour",
    "*Nelson Park  - Katoa St - Alexandra Headland",
    "*Ninderry - Other",
    "*Nirimba - Other",
    "*North Arm - Other - North Arm",
    "*Northern Parklands - Mooloolaba (BA169-170)",
    "*Old Witta School / Community Centre - 316 Witta Rd - Witta",
    "*Palmview - Other",
    "*Palmwoods Piccabeen Green - Little Main St - Palmwoods",
    "*Palmwoods other - Palmwoods",
    "*Park Shelly - 10 Ocean Ct - Shelly Beach (BA276-278)",
    "*Parklakes Drive Park (Ave of Hon) -Parklakes Dr - Bli Bli",
    "*Parklands - Other - Parklands",
    "*Parrearra - Other - Parrearra",
    "*Peace Memorial Park - Maleny St - Landsborough",
    "*Peachester other - Peachester",
    "*Peirce Park - Maroochydore (BA149-150)",
    "*Pelican Waters - Other - Pelican Waters",
    "*Peregian Springs - Other",
    "*Picnic Point Esplanade Park (inc boat ramp & carpark)- Maroochydore",
    "*Pike Park - Oceanic Dr - Warana (BA229-230)",
    "*Pioneer Park - Steve Irwin Way - Landsborough",
    "*Pirate Ship Park - (Pandanus Grove) - Mooloolaba (BA191-193)",
    "*Point Arkwright - Andrew Street Pk - Yinneburra B/land   (BA86)",
    "*Point Arkwright Beach BA86 (Carpark Point lookout)",
    "*Point Arkwright Headlands Dewar St Lookout - (BA85)",
    "*Point Arkwright Headlands Park & lookout/carpark-(BA85-86)",
    "*Point Cartwright Beach  BA196 (Rock Harbour Wall)",
    "*Point Cartwright Beach BA196-206",
    "*Point Cartwright Beach BA197 (Lower Picnic Area Lawn)",
    "*Point Cartwright Beach BA198 (Lighthouse Reserve/Top Lawn)",
    "*Point Cartwright Beach BA199 (Viewing platform)",
    "*Point Cartwright Beach BA200 - (Alan Walker Park)",
    "*Point Cartwright Beach BA201 - (Alan Walker Park)",
    "*Point Cartwright Beach BA204 - (Alan Walker Park)",
    "*Point Cartwright Beach BA205 - (Alan Walker Park)",
    "*Point Cartwright Beach BA206 - (Alan Walker Park)",
    "*Power Memorial Park - Mudjimba",
    "*Power Memorial Park - Mudjimba SLSC grassed area",
    "*Quota Memorial Park  - Nambour",
    "*Railway Street Park - Railway St - Yandina",
    "*Rotary Park - Parkyn Pde - Mooloolaba (BA194)",
    "*Russell Barker Park - Caloundra Rd - Golden Beach",
    "*Russell Family Park  - 25 Western Ave",
    "*Scotmans Park - 189 Oceanic Dr - Warana (BA238)",
    "*Seabreeze Park -8 Melrose Pde - Alexandra Headland (BA151-152)",
    "*Seaforth Park - (Opp Seaforth Resort) - Alexandra Parade Service Rd - Alexandra Headland (BA154)",
    "*Second Bay Beach BA83 - Coolum Beach",
    "*Second Bay Park/Lookout - Coolum Beach (BA83)",
    "*Second Jetty Cotton Tree - The Plaza",
    "*Shelly Beach BA276-281a",
    "*Shelly Beach BA279 (Shelly Beach Pk - Victoria Tce)",
    "*Shelly Beach Park - Victoria Tce & Carpark (BA279-281a)",
    "*Sippy Downs - Other - Sippy Downs",
    "*Sir Leslie Wilson Park -  - Dicky Beach (BA269-270)",
    "*Skippy Park - Old Landsborough Rd - Landsborough",
    "*Stumers Creek Park (Carpark & Reserve) - Coolum Beach (BA69)",
    "*Sugar Bag Road MTB Trails  - Caloundra West",
    "*Sunshine Cove Park -  - Sunrise Drive - Maroochydore",
    "*Tesch Park (Rotary Park) - Coral St - Maleny",
    "*Third Bay Beach - Coolum Beach BA84",
    "*Tickle Park - Coolum Beach",
    "*Tickle Park - Main Park (and stage) - Coolum Beach",
    "*Tickle Park - Picnic Area - Coolum Beach",
    "*Tickle Park - Skate bowl - Coolum Beach",
    "*Trotters Park - (between Boolarong Cres & Alexandra Pde) - Alexandra Headland (BA164&165)",
    "*Tumble Down Park (inc Skate Park ) - Bellara Dr - Currimundi",
    "*Turner Park  - 25 Peachester Rd - Beerwah",
    "*Twin Waters Beach - BA131-136 (North Shore Rd) - Twin Waters",
    "*Twin Waters Beach - BA132",
    "*Twin Waters Beach - BA136",
    "*Viewing Platform -Pacific Blvd - Point Cartwright (BA199)",
    "*Village Green Boulevard Park - Palmview",
    "*Warana Beach BA232 (John Hotton Pk)",
    "*Way St Park/Sportsground Reserve - Mooloolah Valley",
    "*Wilkes Family Park - Alexandra Headland (BA160-161)",
    "*Wilkins Park - Pacific Paradise",
    "*Wilkinson Park - Point Perry Lookout - Coolum Beach",
    "*Woombye - Other",
    "*Woombye IGA - Approved Street Stall Location (SC local charities only) - 20 Blackall St",
    "*Woombye Memorial Park - Blackall St - Woombye",
    "*Woombye News - Approved Street Stall Location (SC local charities only) - 18 Blackall St",
    "*Woorim Park -  Churchill St - Golden Beach",
    "*Wurtulla Beach BA248 (Dorothy Anderson Pk)",
    "*Wurtulla Beach BA249 (Poatina Pk)",
    "*Wurtulla Beach BA250",
    "*Wurtulla Beach BA253",
    "*Wyanda Park -  - Bokarina (BA239)",
    "*Yandina - Approved Street Stall Location - 2 Stevens St",
    "*Yandina - Other - Yandina",
    "*Yaroomba Beach - Yaroomba BA87-90",
    "*Yaroomba Beach BA87 (Yinneburra St)",
    "*Yaroomba Beach BA89 (Yerranya Row)",
    "*Yaroomba Beach BA90 (Warragah Pde)",
    "68a-d)",
    "Balmoral Ridge",
    "Beerwah Library",
    "Glenview",
    "KB & Stage Carparks)  - Kings Beach",
    "Landsborough Other",
    "Maroochydore Other",
    "Montville",
    "Parrearra",
]

event_types = [
    "CLP - AdHoc (CLPA)",
    "CLP - Commercial Use Low - CUL (CUL)",
    "CLP Major Temporary Event (CLPTM)",
    "CLP Temporary Event (CLPTE)",
    "Ceremony/Graduation (AWARD)",
    "Charity Event (CRTY)",
    "Civil Ceremony (CIVIL)",
    "Conference (CONF)",
    "Cultural Event (CULT)",
    "Education - Class (EDCLA)",
    "Film (FILM)",
    "Maintenance (MAIN)",
    "Market/Retail (MKT)",
    "Memorial Service (MEMSE)",
    "Naming Day / Christening (NDCHR)",
    "Other (OTH)",
    "Sport - Competition (SPTCP)",
    "Sport - School (SPSCH)",
]
